export enum DepartmentEnum {
  MINISTRY_ARM = "Ministry Arm",
  HOUSES_ARM = "Houses Arm",
  PROGRAMS_ARM = "Programs Arm",
  EVANGELISM = "Evangelism",
  PRAYER = "Prayer",
  DECORATION = "Decoration",
  CHOIR = "Choir",
  DRAMA = "Drama",
  USHERS = "Ushers",
  PROTOCOL = "Protocol",
  SECURITY = "Security",
  PASTORAL_CARE = "Pastoral Care",
  SANCTUARY_KEEPERS = "Sanctuary Keepers",
  MEDIA = "Media",
  SOUND = "Sound",
  LIGHTING_GENERATOR = "Lighting/Generator",
  CHILDREN_CHURCH = "Children Church",
  TEENS_CHURCH = "Teens Church",
  ICT = "ICT",
}